### ISSUE TITLE
Complete tile tooltips?

### ISSUE THREAD

**Issue by TwistedScorpio** [hjnilsson/rme#101]
Currently in RME there's an incomplete code for drawing tool tips over tiles, basically we could use this to show a tooltip on tiles with action/unique IDs, or even allow ourselves to develop a tooltip for certain items like the editorsuffix one.

**Comment by Mignari** [comment]
Well, wxPaintDC can not be used with wxGLCanvas. So I got some progress with it using glut, but sometimes the text disappear. I've not tested in Linux.

The branch for this issue:
https://github.com/hjnilsson/rme/tree/tooltips

Compiled
https://www.dropbox.com/s/fr9cxz7p25596zy/RME_tooltips.rar

Keyboard shortcut 'Y' to enable.


![image](http://image.prntscr.com/image/73dc8cdf16464120b3fafb8f41523ca0.png)

**Comment by hjnilsson** [comment]
Looks great! Should offset the tooltips by -8 -8 so they're "ontop" of the tiles. :)

**Comment by Mignari** [comment]
This is almost done, but sometimes the text disappears and I don't know how to solve this issue :(

**Comment by Kamenuvol** [comment]
How are you making it? I propose 2 modes of tooltip, fixed like ss and when you hover with mouse
same hotkey to change it disabled> fixed> hover

**Comment by Mignari** [comment]
@Kamenuvol, I made it fixed. Personally, I think that by mouse hover doesn't make sense in a drawable area. Or we want to see, or not see.

@Elime1, can you test this branch on Mac? Thanks.

**Comment by Elime1** [comment]
Seems to be working great since your latest commits. Well done!
