### ISSUE TITLE
Impossible to set town Z position

### ISSUE THREAD

**Issue by ranisalt** [hjnilsson/rme#103]
In one of the more recent commits, something has changed and now it is impossible to change the Z position of a town. It automatically resets to 15 no matter what you type in.

I guess when you type anything it appends to the current value, then checks if it is <= 15, the maximum, and replaces if the entered value is invalid, but it is rendering the town dialogue useless. It is possible to erase either 1 or 5, but impossible to write any other value higher than 4 as it would be >= 15 and reset to 15 again, so not possible to create towns between 6~9.

**Comment by Mignari** [comment]
It works fine for me. What OS are you using?

**Comment by ranisalt** [comment]
Can you please try using higher numbers, preferably between 6 and 9? I can write 1 too.

I'm running Arch Linux, I'll record it for you.

**Comment by ranisalt** [comment]
Here: https://youtu.be/6q6FxRWp8Rg

You can see that while I type "1" with the entire content of the x box selected, it still maintains the 0 there. The same for the second box, it does not allow me to replace selection. For the third box it keeps the content no matter what I type, I'm trying to erase the 15 and type a 7 but the 1 is fixed.

**Comment by ranisalt** [comment]
Thanks!
