### ISSUE TITLE
Just cmake error

### ISSUE THREAD

**Issue by Krzysioka** [hjnilsson/rme#104]
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find LibArchive (missing: LibArchive_LIBRARY
  LibArchive_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindLibArchive.cmake:64 (find_package_handle_standard_args)
  CMakeLists.txt:16 (find_package)

**Comment by zyzof** [comment]
Got the same thing trying to build on Windows and Ubuntu. To anyone running into this issue:
`sudo apt-get install libarchive-dev libwxgtk2.8-dev libwxgtk2.8-dbg`
should sort the issue on Ubuntu. 

Does anyone know how to get this to work on Windows?

**Comment by gpedro** [comment]
`Could NOT find LibArchive`
