### ISSUE TITLE
Ubuntu 14.04 LTS errors run

### ISSUE THREAD

**Issue by ghost** [hjnilsson/rme#109]
webo@webo-GA-MA785GM-US2H:~$ cd rme-master
webo@webo-GA-MA785GM-US2H:~/rme-master$ ./rme
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Review COPYING in RME distribution for details.

** (rme:12394): CRITICAL **: os_bar_hide: assertion 'OS_IS_BAR (bar)' failed

(rme:12394): Gtk-CRITICAL **: IA__gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed

** (rme:12394): CRITICAL **: os_bar_set_parent: assertion 'OS_IS_BAR (bar)' failed

** (rme:12394): CRITICAL **: os_bar_hide: assertion 'OS_IS_BAR (bar)' failed

(rme:12394): Gtk-CRITICAL **: IA__gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed

** (rme:12394): CRITICAL **: os_bar_set_parent: assertion 'OS_IS_BAR (bar)' failed

**Comment by gpedro** [comment]
please, checkout latest version and try again.
