### ISSUE TITLE
export minimap

### ISSUE THREAD

**Issue by ghost** [hjnilsson/rme#110]
when exporting a realmap, the size of the bmp file is like 1gb, and it's not possible to open it up in any programs, tested paint/ps and gimp. It works fine on small maps tho. 

using 3.1

**Comment by Nu77** [comment]
When exporting huge maps the size is ridiculous, saving as png works good though.

**Comment by Emky** [comment]
how did you export as png?

**Comment by Nu77** [comment]
Open with any image editor and just export to png/

**Comment by Emky** [comment]
photoshop: could not complete your request because the file-format module cannot parse the file.
paint: Cannot read this file, this is not a valid bitmap file, or its format is not currently supported.

**Comment by Mignari** [comment]
A solution for this issue will be available soon.
Thanks.
