### ISSUE TITLE
Minimum requirements to compile

### ISSUE THREAD

**Issue by ptkato** [hjnilsson/rme#111]
Does it have any? Because I'm trying to compile in a computer with 3GB RAM (let's say that 400mb of these 3GB are occupied by the OS and desktop environment) and I can't seem to be able to finish it, when the compilation process reaches the templatemap81.cpp it just eats all the remaining memory and almost freeze the computer. [An image for reference](http://i.imgur.com/kgg9iMm.jpg).

Through the process, it doesn't even reaches 600MB of used RAM, but it suddenly goes up and eats everything, is this behavior expected? Last time I compiled this (sometime in middle last year), it was in a computer with 4GB of RAM and I don't remember facing any problems. Both situations were under Debian Jessie x64.

**Comment by diath** [comment]
Try removing out these huge vectors from version templates, that should do the trick.

**Comment by hrsantiago** [comment]
I just removed this file from cmakelists, it's not even used if I recall right.

**Comment by Mignari** [comment]
This happened to me a few times. I just changed set(CMAKE_BUILD_TYPE RelWithDebInfo) to set(CMAKE_BUILD_TYPE Release) to solve it.

CMakeLists.txt line 6

**Comment by ptkato** [comment]
Yeah, changing RelWithDebInfo to Release did the trick.
