### ISSUE TITLE
select copy feature

### ISSUE THREAD

**Issue by ghost** [hjnilsson/rme#115]
Is it possible to get a feature like this:

say if i searched for a 'statue id' for example, after there would be an option to select all the statues with that ID in every floor at the same time, and then be able to copy them all

I don't know if it already exists or not, but if someone could add support for that, it would be sick

**Comment by hjnilsson** [comment]
That's a really specific and weird feature. Why do you need this?

**Comment by Emky** [comment]
trying to copy over specific items from an old map i have, would save me alot of time

**Comment by hjnilsson** [comment]
This is a too specific feature to implement in the editor, perhaps if lua scripting or something similar is done, it could be scripted instead. Closing.
