### ISSUE TITLE
Feature Request: Live mapping

### ISSUE THREAD

**Issue by N0xZz** [hjnilsson/rme#116]
Hey guys,

some time ago there was a beta version of RME with the "live mapping" function. It didnt work well but i love the idea to map together.
I think this feature would be really amazing. If it works properly, this could be a huge help for any teamprojects.

Because I dont know how much effort this would take, I thought let's just request it.

In my vision this function could be like a client/server principle. You could host a "map server" which has functions like autosave and doesnt close when there's nobody online. In remere there could be a "join" button to connect to the server. 

Can't wait to get some reply. I hope this is possible, I'd love to have it :smile: 

Best Regards,
Noxz

**Comment by comedinha** [comment]
https://github.com/hjnilsson/rme/blob/master/data/menubar.xml#L120

**Comment by N0xZz** [comment]
yea as i said there was this function. But sadly it didnt work well. It seems like it's going out of sync or something. Sometimes after some seconds sometimes it's good for some minutes. I thought someone could look at it. Maybe it would be more stable if the "server" is an own exe?

Thanks for reply so far :tongue:
