### ISSUE TITLE
Dat signature: 4C2C7993

### ISSUE THREAD

**Issue by EmersonHenriique** [hjnilsson/rme#120]
01:32:45: Signatures are incorrect.
Dat signature: 4C2C7993
Spr signature: 4C220594

**Comment by gpedro** [comment]
which version are you using?

**Comment by EmersonHenriique** [comment]
Tibia 8.60 rme 2.2

**Comment by EmersonHenriique** [comment]
Tibia 8.60v2

**Comment by gpedro** [comment]
4C2C7993 and 4C220594
It's signature of the old version.
> https://github.com/hjnilsson/rme/blob/master/data/clients.xml#L171-L174

**Comment by EmersonHenriique** [comment]
Yes, it's an old version , however how do I get to use the rm in this version ?

**Comment by Mignari** [comment]
Update your RME to the last version. The version 2.2 is outdated
https://github.com/hjnilsson/rme/releases

Or try unchecking the 'Check file signatures'.
File > Preferences > Client Version

**Comment by EmersonHenriique** [comment]
I will download the 3.1 version , I unchecking the ' Check file signatures ' .
File> Preferences> Client Version and yet the error

**Comment by EmersonHenriique** [comment]
using version 3.1 will solve the problem ?

**Comment by EmersonHenriique** [comment]
Works using version 3.1, however now I need help, I need to add in rm a block respawn function, when I create a spawn of a monster have the option of whether it will be blocked or not {true or false}

**Comment by EmersonHenriique** [comment]
http://i.imgur.com/RhQaFd4.png

**Comment by lukatxd** [comment]
I'm having this issue on 3.6.1. Unchecking file signature causes RME to crash.
