### ISSUE TITLE
Can't see map

### ISSUE THREAD

**Issue by Krzysioka** [hjnilsson/rme#123]
Like topic says, i can't view maps on my rme map 
editor.[http://speedy.sh/jVb3d/Przechwytywanie.PNG](url)
It happens on evry map, no matters which it is client version

**Comment by gpedro** [comment]
which your operating system?

**Comment by Mignari** [comment]
Make sure Only show colors and Only show modified are unchecked.



![image](http://image.prntscr.com/image/88f79448221049fcbbab446821aa4319.png)

**Comment by Krzysioka** [comment]
still nothing, i've got windows 7 and rme from github. When map is loaded (i am sure that it;s loaded cuz of i can draw but cant see what i am drawing etc) vision is bugging,

**Comment by Krzysioka** [comment]
http://speedy.sh/UAjyK/Przechwytywanie.PNG it stuck like this
