### ISSUE TITLE
Requested Feature: More brush sizes

### ISSUE THREAD

**Issue by mattshadowwing** [hjnilsson/rme#124]
Hello, I know that this may be a minor feature to request (or i could possibly do it myself if i had a tiny bit more knowledge) but i'd like to have more brush sizes, specifically ones with even numbers for more detailing and more robust mapping styles and details.

the entire brush system can be turned into the following:
drown down or icons for brush type (square or circle or more)
a drop down or text input for brush size where the user can select or input the size of the brush that he wishes

one issue that might happen with evennumber size brushes is centering the brush curser on the map, this problem might seem bigger than it seems but i think the user will get used to using it as long as it is consistent.
For example even brushes will always be off-centered by 1 square to the top left instead of being dead center like odd number size brushes.

Anyway i hope this feature gets a greenlight and some form of priority or even the attention of a contributor as it will increase the quality of mapping in the OT community as a whole.

Thanks

**Comment by hjnilsson** [comment]
Drop down / text input both require multiple clicks to interact with. While the current system only requires one click. It would be a regression in usability in my opinion.
