### ISSUE TITLE
Enhanced features - zones and pins

### ISSUE THREAD

**Issue by kuzynn** [hjnilsson/rme#128]
What do you think about upgrading RME? It would be awesome to have something like zones/areas system and pins (not game objects ofc, only for map makers). 

**Features of zones:**
- You can draw it on any ground you want
- You can name your zone
- You can add description (no more writing in wordpad/word)
- You can check all monsters and their amounts in zone
- You can check all unique and action ids in zone
- You can check all writeables in zone
- You can check all containers in zone
- You can check all NPCs in zone
- You can check all specific pins in zone

**Features of pins (you know that you want add something but you don't have it for now):**
- You can make a "NPC pin" (name, description)
- You can make a "Monsters pin" (name, description)
- You can make a "Quest pin" (more complicated quests can have few pins in the same colour)
- You can make a "My pin" (everything that is not a monster, npc or quest)

**Comment by HeavenIsLost** [comment]
i like this feature but i also want to say that the major problem with remeres editor(because of the otbm format) is there is no way to multiple team members edit the map at the same time. The map uses a binary file format that overrides any changes someone did and there is no way to merge map edits.

**Comment by kuzyn1** [comment]
For me, live mapping is not necessary. These features are for offline mapping.

**Comment by kuzyn1** [comment]
For me, live mapping is not necessary. These features are for offline mapping.

**Comment by kuzyn1** [comment]
For me, live mapping is not necessary. These features are for offline mapping.

**Comment by kuzyn1** [comment]
@gpedro 
Hm?
