### ISSUE TITLE
Implement Lua scripting.

### ISSUE THREAD

**Issue by Mignari** [hjnilsson/rme#131]
OT world has a lot of skilled Lua programmers. This will enable them to implement new features like procedural map generation, custom area selection and move, custom item replacement, etc.

**Comment by hjnilsson** [comment]
Would be a excellent addition. Will need some thought on how to implement it in the UI, though.

**Comment by Mignari** [comment]
Initially, I will expose/bind some edition functions and load an external script when the application is opened.
The wxWidgets has a nice code editing component.
http://docs.wxwidgets.org/trunk/classwx_styled_text_ctrl.html
Maybe we can implement within the application.
