### ISSUE TITLE
wxT macro not needed anymore

### ISSUE THREAD

**Issue by Elime1** [hjnilsson/rme#141]
As of wxWidgets 3.0 wxT() is not needed anymore: http://docs.wxwidgets.org/3.0/overview_changes_since28.html
Should we stick to using wxT anyway or maybe run a script to remove them all?
I'm just asking because I just committed changes without using wxT() =P

**Comment by Mignari** [comment]
This is a good code cleanup.

**Comment by gpedro** [comment]
LGTM
