### ISSUE TITLE
New Toolbar

### ISSUE THREAD

**Issue by totolol123** [hjnilsson/rme#144]
RME should have a toolbar for menu actions, would be good if we can change position (horizontal/vertical) too.
Also Zoom and Floor up/down and Minimap can be added to toolbar and maybe Go to Position can be a input field

something like that:
http://i.imgur.com/rlph1KA.jpg

**Comment by hjnilsson** [comment]
I strongly disagree with this change. If it is done it should definitely be an option, not a change of UI.

**Comment by Elime1** [comment]
#23

**Comment by Mignari** [comment]
I like it. It can be dockable and the user will decide the position. But I'll wait for more votes/opinions.

**Comment by totolol123** [comment]
Actual UI behavior is pretty bad, important tools should be in a top position for a clean view and better use. What the hell is the point of having two or more pallete and the same brush size option? Also what about using only one pallete and the need of focusing terrain for using important tools? I think this is a good approach for a better design and improve user usability.
