### ISSUE TITLE
Dark theme option

### ISSUE THREAD

**Issue by totolol123** [hjnilsson/rme#145]
Dark themed (like photoshop) option for RME

**Comment by Elime1** [comment]
wxWidgets is using native components as much as it can, therefore theming can be very tricky. wxAui is relatively easy to alter but I think things like the menu bar and scroll bars will be problematic. Especially to make it work cross-platform. Anything is possible but it might take a lot of time and effort. =P

**Comment by totolol123** [comment]
I think it's not worth the effort so will close it
