### ISSUE TITLE
Placeable field with tooltip

### ISSUE THREAD

**Issue by totolol123** [hjnilsson/rme#152]
Could be great a tool for placing a field (like spawn/waypoint) and after editing it's content (like writable items) popping up a tooltip with the written text, can be usefull for placing important information on map like a long quest with multiples NPC.

**Comment by Kamenuvol** [comment]
Could be useful with (a stack of) containers see all contents at once, separated by a line.

**Comment by hjnilsson** [comment]
This is very similar to: https://github.com/hjnilsson/rme/issues/101

Do we need both?

**Comment by totolol123** [comment]
If we have tooltip already just do it show in waypoints and we are fine.
