### ISSUE TITLE
Change creature direction and rotate items with keyboard arrow

### ISSUE THREAD

**Issue by totolol123** [hjnilsson/rme#155]
Would be great having that.

**Comment by hjnilsson** [comment]
Right now arrow keys are used to move around the map. Should we replace that?

**Comment by Kamenuvol** [comment]
Is Ctrl + Arrow used? Would be better for it

**Comment by Dark199** [comment]
There is already a key for that, z and x, if that's what you mean

**Comment by totolol123** [comment]
There's not. Tried it with rotatable items and nothing happens. Crtl + arrow looks good for me.

**Comment by Dark199** [comment]
Didn't see your edit, that was what I was talking a out
