### ISSUE TITLE
Can't open map when the editor is running

### ISSUE THREAD

**Issue by Elime1** [hjnilsson/rme#167]
On Windows I can't open an .otbm file by clicking it when the editor is already running. It doesn't work in RME 3.0 release either. Is IPC broken?

**Comment by Olrios** [comment]
Same issue was 5 years ago with 2.0
It's still not fixed. So, label should be set to confirmed becouse this isn't sth new

**Comment by Elime1** [comment]
Well, now you confirmed it. =P
