### ISSUE TITLE
Compile problem Ubuntu 16.04

### ISSUE THREAD

**Issue by joan97** [hjnilsson/rme#170]
Hello,

Its my first time installing rme, and i already have a problem hehehe, in the last step make -j `nproc` give me an error, i installed some dependencies were people recomended but still give me this error.
If someone can told me what dependencies are missing or what is the problem that will be great thanks.

![image](https://cloud.githubusercontent.com/assets/24464799/21030504/2c14a8b8-bd9f-11e6-8abb-c574595c66f1.png)

**Comment by Mignari** [comment]
Make sure you have wxwidgets 3.1

**Comment by joan97** [comment]
I had 3.0.2 wxwidget version, now i have installed 3.1.1 but still the same errors :S, thanks for trying to help me anyway.

![image](https://cloud.githubusercontent.com/assets/24464799/21033933/6f0b164c-bdb4-11e6-96d7-64e4a7705634.png)

**Comment by Elime1** [comment]
Did you try to delete the build folder and then follow the steps again from where you create a build folder. cmake should output some info about what version of wxWidgets it found.

**Comment by joan97** [comment]
I forgot to deleted the folder ups, now i deleted and followed the steps again but a similar error appears :/ 

![image](https://cloud.githubusercontent.com/assets/24464799/21054701/f45a7142-be2e-11e6-8f39-dfe0903b5d11.png)

**Comment by Elime1** [comment]
Run `git pull origin master` and it should be working for you.

**Comment by joan97** [comment]
I fixed the problem it was just a little thing

I had to go /rme/source/map_drawer.cpp and modify the #include <glut\glut.h>      for  
#include <GL\glut.h>

![image](https://cloud.githubusercontent.com/assets/24464799/21064647/45649edc-be5c-11e6-9361-575b590488fd.png)

Thanks for trying to help me anyway Elime1
