### ISSUE TITLE
Error opening rme Ubuntu 16.04 

### ISSUE THREAD

**Issue by joan97** [hjnilsson/rme#171]
Hello again, i have another problem :(
When i try to open rme looks like it will open but suddenly closses. 
I executed in terminal and this error appears i searched something but i don't really understand what is happening.

![image](https://cloud.githubusercontent.com/assets/24464799/21073609/8e8b28e2-bee3-11e6-8295-fb13d0b9e1b2.png)

And this is the code of the error /src/unix/glx11.cpp   i didn't modified anything of this file.

![image](https://cloud.githubusercontent.com/assets/24464799/21073631/4d89dfc2-bee4-11e6-8644-84b3382310b0.png)

**Comment by Mignari** [comment]
Same here. I'll investigate what change breaks it

**Comment by Mignari** [comment]
My crash was caused by non initialization of glut and extension loading (see #98), but it doesn't seems to be the same problem here.

**Comment by joan97** [comment]
I will continue searching some information. 
It's probably some nonsense and maybe other guys had the same problem and can help me to fix this problem i hope :p .

**Comment by Elime1** [comment]
Is this still a problem?

**Comment by joan97** [comment]
Yes, i can't fix this problem :/
