### ISSUE TITLE
Tooltip not displaying text

### ISSUE THREAD

**Issue by totolol123** [hjnilsson/rme#175]
As title says it show nothing in tooltip, using OS X.

**Comment by Elime1** [comment]
It works for me. Maybe you zoomed out too far?
![tooltip](https://cloud.githubusercontent.com/assets/9988754/21851976/ae71861e-d811-11e6-856f-4e56c0af2034.png)

**Comment by gpedro** [comment]
tooltips just works with 100% of zoom... maybe we can remove tooltip when zoom is below 100%

**Comment by Elime1** [comment]
But then you can't tell if tooltips are active or not when you are zoomed out

**Comment by Geseth** [comment]
If that so how about to change icon for tooltip when we change zoom to other then 100%, for example to some map pointer like in google maps?
