### ISSUE TITLE
Scaling on some windows

### ISSUE THREAD

**Issue by shocx** [hjnilsson/rme#176]
Hey there, got this issue on some windows shown in the screens below. Some parts of the window is inaccessable cause i cant move the outer border.
Here are two examples: 
<img width="288" alt="import" src="https://cloud.githubusercontent.com/assets/25158768/21998723/d2176768-dc36-11e6-9b17-96f752bb4afd.PNG">
<img width="321" alt="town" src="https://cloud.githubusercontent.com/assets/25158768/21998724/d5840992-dc36-11e6-8ead-edf6dd0c4876.PNG">

Maybe it's related cause I got a 4k Monitor, got a 1080p before and never had that problem

**Comment by Elime1** [comment]
What happens if you change the resolution to 1920x1080?

**Comment by shocx** [comment]
If I change to a 1920x1080 monitor there is no problem. So it seems to be the 4k resolution

**Comment by Elime1** [comment]
I do not have a 4k monitor but I tested using different scaling and I could see the same problems as you describe using RME 3.2. But not if I use a version compiled with wxWidgets 3.1. HiDPI support imporved in wxWidgets 3.1. So this should not be a problem in the upcoming RME 3.3 release.

**Comment by Elime1** [comment]
Can someone with a 4k monitor confirm that this problem is gone in RME 3.3?

**Comment by shocx** [comment]
Yeah I can confirm it. For me it's gone :)

**Comment by Elime1** [comment]
Great!
