### ISSUE TITLE
items bug

### ISSUE THREAD

**Issue by daniofordon** [hjnilsson/rme#177]
hello I have a little problem with rme editor map for some time on each tab missing graphics for mapping I do not know why it happened

as you can see is only a few graphics and so on each tab

http://snap.ashampoo.com/xwRl7hrM

I will add that I have so each time the map editor, and regardless of whether I will remove it and all remnants of it, and so all the time is the problem

had someone can this problem and knows how to solve it?

**Comment by Elime1** [comment]
That is the standard amount of brushes in Terrain Palette > Cave

**Comment by daniofordon** [comment]
This is just an example of the other tabs missing many items

**Comment by Elime1** [comment]
So is this pretty much the same as #180 ? Or did something disappear that previously existed?
