### ISSUE TITLE
Tibia 8.60 Version

### ISSUE THREAD

**Issue by Skrillaz** [hjnilsson/rme#179]
Why remeres section Clients doesent have tibia 8.60 ?? i need it

**Comment by hjnilsson** [comment]
Hello,

Unfortunately, google flagged that file as containing viruses (which is not true... but there is no way to communicate that to Google) and removed the website from all google search results (and put up virus warnings in all browsers). I cannot add a link to the file again without removing the website from Google, unfortunately.

If anyone has any suggestions on how to PREVENT google from flagging random .exe files as viruses, it'd be most welcome. :)

**Comment by kalikovsky** [comment]
Just archive it with encryption and hide filenames, google won't be able to flag it.

**Comment by d8douglas** [comment]
Thats righty @kalikovsky if @hjnilsson encrypt the filenames, they would never find and block the download. Cipsoft is trying to end up with all the ots, and maybe they are with google doing that.
@hjnilsson I need that 8.6, can u upload somewhere? i have lost it

**Comment by hjnilsson** [comment]
The file is still available here: https://remeresmapeditor.com/files/tibia/tibia860.exe
