### ISSUE TITLE
when will you FINALLY update the terrain palette?

### ISSUE THREAD

**Issue by woeterman94** [hjnilsson/rme#180]
In my option the palettes need an update... New floors, walls, doors, trees etc... are not available in palettes ... Is it possible to upgrade these..

**Comment by kalikovsky** [comment]
You can easilly update those files to your liking, there's a bunch of xml files that do just that in your data folder.

**Comment by hjnilsson** [comment]
If you do update the files, please also submit a pull request here so more people can use your improvements. :)
