### ISSUE TITLE
No text field on signs

### ISSUE THREAD

**Issue by LuisPro** [hjnilsson/rme#181]
hello, i dont have fields to edit text on signs (letters, blackboards is ok)

its happen on:
rme: Latest release
client version: 7.6
map version: 0.6.0

![gif](https://cloud.githubusercontent.com/assets/6198792/23588942/42bb2dca-01c5-11e7-8262-9804ed2b768f.gif)

**Comment by peonso** [comment]
Signs and other items as statues should be added to https://github.com/hjnilsson/rme/blob/master/data/760/items.xml
