### ISSUE TITLE
[SUGESSTION]Replace item/grass/terain/all  with item/grass/terain/all 

### ISSUE THREAD

**Issue by TibiaFun** [hjnilsson/rme#182]
hey, will be nice if will be option to change item with item / change all items =777 to items 666
grass = 555id replace all on to id 556
it will be helpfull for custom server etc easy conwert map on bigger protocol.

sorry my english. :D

**Comment by Elime1** [comment]
Doesn't this already exist with: Edit  -> Replace item... ?

**Comment by Codex-NG17** [comment]
Yea but you are limited to 500 instances of that itemid.
