### ISSUE TITLE
Crashing at save

### ISSUE THREAD

**Issue by Emilianenko** [hjnilsson/rme#188]
when i use the toll remove all unreachable tiles ,and try to save the map, he crashes at 99%  =(

**Comment by bpawel10** [comment]
I can confirm I have the same issue.

**Comment by Costallat** [comment]
The problem is when it removes some tile that have some creature or spawn on it.

**Comment by Costallat** [comment]
@hjnilsson can you give me permission to commit?

I have a small fix for this.

Tks.

**Comment by hjnilsson** [comment]
Added as a contributor. :)

**Comment by bpawel10** [comment]
Why doesn't he just create pull request?

**Comment by bpawel10** [comment]
So you probably did it wrong way. As far as I know you should fork this repo and push your branch there.

**Comment by gpedro** [comment]
@dalkon fork this repository, if already cloned the project, change origin url to fork url and push your branch.

**Comment by Costallat** [comment]
@bpawel10 So it's not that I did it wrong, I just didn't followed the Github process.

@gpedro Thanks for the explanation.

So I created a file to be used to reproduce the problem, you can open that map, clean it with the "unreachable tile" feature, and it will crash when you save it.

[crash.map.tar.gz](https://github.com/hjnilsson/rme/files/2275856/crash.map.tar.gz)

#236 

This is a v.0.1 version to the fix, as it doesn't show any message to inform the user that his map has those wrong spawn points, but it avoids the crash.
