### ISSUE TITLE
Copy position

### ISSUE THREAD

**Issue by coldensjo** [hjnilsson/rme#190]
Change copy position so it copies
`(X, Y, Z)`

instead  of
`{x = X, y = Y, z = Z}`

**Comment by slawkens** [comment]
This should be configurable.

**Comment by hjnilsson** [comment]
It is formatted that way to make it easily pasteable into lua scripts. I assumed this is the most common reason to copy position.

For what scenario do you need another format?

**Comment by coldensjo** [comment]
Because that format is never used.
[http://i.imgur.com/xBNRV5S.jpg](http://i.imgur.com/xBNRV5S.jpg)
