### ISSUE TITLE
What happened to live mapping?

### ISSUE THREAD

**Issue by ghost** [hjnilsson/rme#197]
I know you can enable it by uncommenting in menubar.xml, but from my testing it doesn't work anymore. Was it abandoned? It was the greatest feature.

**Comment by 2-r-e-c** [comment]
If i remember correctly, it was abandoned due to problems with synchronization in .otbm file extension.
A little late, but what the hell, maybe someone would be looking for answer :v

**Comment by OchmanM** [comment]
@hjnilsson are there any plans on restoring this module?
