### ISSUE TITLE
Minotaur Archer, Squirrel & Cobra looktypes bugged

### ISSUE THREAD

**Issue by ghost** [hjnilsson/rme#198]
These creatures have their looktypes bugged for some reason, this also happens ingame with OtClient but not with 10.98 cip client.

[http://i.imgur.com/riizIhT.png](http://i.imgur.com/riizIhT.png)

See: [otclient/issues/813](https://github.com/edubart/otclient/issues/813)
See: [http://i.imgur.com/acA42wW.png](http://i.imgur.com/acA42wW.png)

**Comment by Riverlance** [comment]
This thread mine is important too: https://github.com/edubart/otclient/issues/852

**Comment by zeeb92** [comment]
This is still relevant and has been for 3 years.
Come on guys.
