### ISSUE TITLE
Map does not open

### ISSUE THREAD

**Issue by Joberval** [hjnilsson/rme#199]
The program does not open the map, I have other friends with the same problem, until mini map appears, but the map itself does not open, do you know if it is a configuration, bug, etc?
Windows 7 ultimate 64x - RME_Winx64_3_3.exe

![capturar](https://user-images.githubusercontent.com/29413697/27103811-55dfb558-5060-11e7-8921-efd034bd484d.PNG)

**Comment by Elime1** [comment]
Did you try the 32 bit version?

**Comment by GodKimber** [comment]
i have this problem too. 32 bits :(

**Comment by Joberval** [comment]
Yes, I've tried it and version 3.2 works perfectly, anyway I'm using it. Forgive me if English is bad, I'm Brazilian, I'm using google translator.

**Comment by sirakx** [comment]
The same happens to me, I have win10x64

**Comment by Elime1** [comment]
I have tested on two different windows 10 machines and so far I have not been able to reproduce this problem.
