### ISSUE TITLE
Big Bug on windows 10 profesionall platform x64

### ISSUE THREAD

**Issue by glombers** [hjnilsson/rme#202]
![enter image description here](http://i.imgur.com/0puJL3K.gif)
I do not know how this is caused but maybe it would be better to open the map 2 separate window

**Comment by Zaaku12** [comment]
Same here :/
Win 10 x64

**Comment by Elime1** [comment]
This was already reported in #199. But thank you for the animation you posted. It makes it clear what the problem is, so I will keep this issue open.

**Comment by Maazik** [comment]
Same problem here.
