### ISSUE TITLE
RME 3.3 new Features don't work :(

### ISSUE THREAD

**Issue by Rafamon** [hjnilsson/rme#204]
It's as if I was using and older version, there is no option to play animations or see tooltips anywhere.

**Comment by armadaazteca** [comment]
You have to make sure the data/menubar.xml file gets updated too, not just the exe

**Comment by glombers** [comment]
https://github.com/hjnilsson/rme/pulls

**Comment by Elime1** [comment]
As armadaazteca said you might be using the old data folder. The options are under View menu and the shortcuts are Y and L.
