### ISSUE TITLE
Working for Tibia 10.00?

### ISSUE THREAD

**Issue by kito2** [hjnilsson/rme#207]
Hey everyone,

There is a repo working with Tibia 10.00 and 11.00, it is https://github.com/malucooo/Otxserver-New and they have an update items.otb and items.xml.

I was wondering if you could update the map editor to work with those versions?

Thanks!

**Comment by diath** [comment]
The updated items.otb could become incompatible with TFS in the future rendering your map useless without a converter tool so I don't think it's desirable to have RME working with these unofficial files.
