### ISSUE TITLE
Replace item always replace item and place it on top

### ISSUE THREAD

**Issue by nekiro** [hjnilsson/rme#209]
For example replace any ground with other one with items above it.
Ground will be the top top item and shouldnt be.

**Comment by Elime1** [comment]
I could not reproduce this. I placed some ground tiles and som items above it. Then i selected the ground tiles and went to edit -> Replace item and replaced the ground tiles with an other type of ground tile. The items were still on top of the ground tiles.

**Comment by nekiro** [comment]
Did you try with walls or normal movable items?

**Comment by Elime1** [comment]
Normal movable items
