### ISSUE TITLE
Bugs with custom client

### ISSUE THREAD

**Issue by ricardoianelli** [hjnilsson/rme#210]
Hi, i've created a brand new .spr and .dat (clean) and just added the stuff i wanted, but when trying to use it with the RME it bugs a lot, even going to raw>others, no sprite appear or appear bugged, like that:
![image](https://user-images.githubusercontent.com/2482654/29992178-c349f3fc-8f6b-11e7-864e-8cbd42fd21d5.png)

Do i need to change something? Im using custom .otb too.

**Comment by AngelOfDeaths** [comment]
i have the same problems on 10.41 with transparenty items.otb
