### ISSUE TITLE
Empty brushes after clean compile

### ISSUE THREAD

**Issue by Kerooker** [hjnilsson/rme#213]
![image](https://user-images.githubusercontent.com/1577251/31106053-e8514694-a7be-11e7-89f7-466ac9295ba4.png)

Empty brushes after a complete clean installation, the brushes do work, however:

![image](https://user-images.githubusercontent.com/1577251/31106065-fe1e6f10-a7be-11e7-9bdd-bed8c97b68d4.png)

**Comment by EnzzoCaaue** [comment]
confirmed on linux mint.

**Comment by Kerooker** [comment]
I was using mint indeed. What more information is needed?

**Comment by Elime1** [comment]
Can you confirm if it works now?

**Comment by Kerooker** [comment]
It did fix, yes.
