### ISSUE TITLE
Compiling on ubuntu (mint)

### ISSUE THREAD

**Issue by EnzzoCaaue** [hjnilsson/rme#214]
cmakeerrorlog.log:
https://pastebin.com/TmCaQ1pw
cmakeoutput.log:
https://pastebin.com/wPAhJg7p
terminal:
https://pastebin.com/Qa9f4A4s

**Comment by Kerooker** [comment]
Did you take a look at [this](https://github.com/hjnilsson/rme/wiki/Compiling-on-Ubuntu)?

**Comment by Elime1** [comment]
You are missing a compiler. Try: apt-get update && apt-get install build-essential

**Comment by EnzzoCaaue** [comment]
@Kerooker yup, I did.

@Elime1 I'll try it when get home.

**Comment by EnzzoCaaue** [comment]
Thanks @Elime1 !
solved, anyone feel free to close this.
