### ISSUE TITLE
Bug VM with xubuntu

### ISSUE THREAD

**Issue by jokamikaze** [hjnilsson/rme#217]
i don't know if it's a VM bug, or RME bug. 
some cases when i open one map the screen that you edit (i dunno the name) will appear in front of the ubuntu processes. example, if u press rmb at somewhere close to the "screen that you edit". the window will appear behind.
print:
![image](https://user-images.githubusercontent.com/24738622/31754156-77e05bf8-b474-11e7-9097-431e2351ca0c.png)
but if i  shoot a print inside the VM show "normaly"
![bug](https://user-images.githubusercontent.com/24738622/31754203-e0caf2ea-b474-11e7-94f4-c31eb6473098.png)
(sorry my english)

**Comment by Elime1** [comment]
It is a VirtualBox issue. It will happen with any window using 3D acceleration.
https://www.virtualbox.org/ticket/12738
https://www.virtualbox.org/ticket/12383
