### ISSUE TITLE
Polish diacritic marks doesn't save correct in map file

### ISSUE THREAD

**Issue by Geseth** [hjnilsson/rme#219]
I read whole issue categorie and Im not found any symilar topics so it's here now ;) Some important info:
* RME 3.3
* Client 8.6
* Win 8.1 pro 64

I would like to prepare some text in native language but when i write and save map, game doesn't show it correctly.

![polish diacritic marks bug](https://user-images.githubusercontent.com/6680211/32469357-8df95ede-c352-11e7-80f5-5a626d4dca66.png)

In editor it looks correct, but in tooltips that marks disapear...

![polish diacritic marks bug2](https://user-images.githubusercontent.com/6680211/32469358-8e179fc0-c352-11e7-91cb-47ee3d0276ca.png)

and editor save, in map file, some other marks (view from HxD - hex editor):

![polish diacritic marks bug3](https://user-images.githubusercontent.com/6680211/32630789-3a523c94-c59e-11e7-90a6-ccc4d4e93d7c.png)

I think its because RME save it in other format than UTF-8 (maybe in ASCII). Even that, when I open saved map file (using RME), I can freely read and edit that text in Item propertis. So it works but only in a half-way. I've try to investigate the source of problem but I'm not good in programing so I've stop after reading source code of only one file: properties_window.cpp.

**Comment by gpedro** [comment]
@Mignari can you help with this?

**Comment by Elime1** [comment]
We are using a glut bitmap to render text so this is pretty much what you get:

![glut_bitmap_helvetica_18](https://user-images.githubusercontent.com/9988754/32980672-1674a054-cc6b-11e7-85f6-4ce23360196c.png)
