### ISSUE TITLE
Selection using slow data structure

### ISSUE THREAD

**Issue by zygzagZ** [hjnilsson/rme#234]
Why does selection.cpp use TileVector to hold selection tiles? I am not sure whether it is placebo, but I noticed it to be much faster when using unordered_set aka. hashset. I know of no cons of using hashset instead of vector, and it has the advantage of fast element removal in expected complexity O(1) as opposed to O(n) in vector... Effect: undoing addition to a big selection is almost instant rather than taking forever...
Is there any story about using vector, or was it just coded that way? 
I'd be glad to share a patch with community should anyone care about this

**Comment by Elime1** [comment]
Don't know if there is a reason. Feel free to make a pull request and show how much improvement it gave.

**Comment by Sickness-chan** [comment]
Performance improvements are always good to have. Sometimes I get bothered by it myself if I select a big area and then unselect it and it takes a while to complete that process. Would like to see a patch for it.

**Comment by zygzagZ** [comment]
Made PR #254
