### ISSUE TITLE
OSX Compilation

### ISSUE THREAD

**Issue by Bennet92** [hjnilsson/rme#24]
Tried to compile it on OSX 10.9 with an cmake created Xcode project (all the linking stuff works), however I get the following errors:

In file included from /Users/bennet/Downloads/rme-master/source/extension_window.cpp:9:
In file included from /Users/bennet/Downloads/rme-master/source/gui.h:31:
In file included from /Users/bennet/Downloads/rme-master/source/map_tab.h:24:
In file included from /Users/bennet/Downloads/rme-master/source/application.h:28:
/Users/bennet/Downloads/rme-master/source/map_display.h:88:7: warning: 'MapCanvas::Refresh' hides overloaded virtual function [-Woverloaded-virtual]
        void Refresh();
             ^
In file included from /Users/bennet/Downloads/rme-master/source/extension_window.cpp:5:
In file included from /Users/bennet/Downloads/rme-master/source/main.h:48:
In file included from /usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/wx.h:38:
In file included from /usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/window.h:1915:
/usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/osx/window.h:84:18: note: hidden overloaded virtual function 'wxWindow::Refresh' declared here
    virtual void Refresh( bool eraseBackground = true,
                 ^
/Users/bennet/Downloads/rme-master/source/extension_window.cpp:61:2: error: "NOT IMPLEMENTED"
#error "NOT IMPLEMENTED"
 ^
In file included from /Users/bennet/Downloads/rme-master/source/extension_window.cpp:9:
In file included from /Users/bennet/Downloads/rme-master/source/gui.h:26:
In file included from /Users/bennet/Downloads/rme-master/source/copybuffer.h:26:
In file included from /Users/bennet/Downloads/rme-master/source/basemap.h:13:
/Users/bennet/Downloads/rme-master/source/map_allocator.h:11:11: warning: private field 'map' is not used [-Wunused-private-field]
        BaseMap& map;
                 ^
2 warnings and 1 error generated.

AND:

In file included from /Users/bennet/Downloads/rme-master/source/gui.cpp:9:
In file included from /Users/bennet/Downloads/rme-master/source/gui.h:31:
In file included from /Users/bennet/Downloads/rme-master/source/map_tab.h:24:
In file included from /Users/bennet/Downloads/rme-master/source/application.h:28:
/Users/bennet/Downloads/rme-master/source/map_display.h:88:7: warning: 'MapCanvas::Refresh' hides overloaded virtual function [-Woverloaded-virtual]
        void Refresh();
             ^
In file included from /Users/bennet/Downloads/rme-master/source/gui.cpp:5:
In file included from /Users/bennet/Downloads/rme-master/source/main.h:48:
In file included from /usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/wx.h:38:
In file included from /usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/window.h:1915:
/usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/osx/window.h:84:18: note: hidden overloaded virtual function 'wxWindow::Refresh' declared here
    virtual void Refresh( bool eraseBackground = true,
                 ^
/Users/bennet/Downloads/rme-master/source/gui.cpp:98:39: error: unknown type name 'AGLPixelFormat'; did you mean 'WXGLPixelFormat'?
        OGLContext = new wxGLContext((AGLPixelFormat)AGL_RGBA, (wxGLCanvas*)nullptr, unused, nullptr);
                                      ^~~~~~~~~~~~~~
                                      WXGLPixelFormat
In file included from /Users/bennet/Downloads/rme-master/source/gui.cpp:5:
In file included from /Users/bennet/Downloads/rme-master/source/main.h:43:
/usr/local/Cellar/wxmac/3.0.0.0/include/wx-3.0/wx/defs.h:3142:32: note: 'WXGLPixelFormat' declared here
typedef WX_NSOpenGLPixelFormat WXGLPixelFormat;
                               ^
/Users/bennet/Downloads/rme-master/source/gui.cpp:98:54: error: use of undeclared identifier 'AGL_RGBA'
        OGLContext = new wxGLContext((AGLPixelFormat)AGL_RGBA, (wxGLCanvas*)nullptr, unused, nullptr);
                                                     ^
In file included from /Users/bennet/Downloads/rme-master/source/gui.cpp:9:
In file included from /Users/bennet/Downloads/rme-master/source/gui.h:26:
In file included from /Users/bennet/Downloads/rme-master/source/copybuffer.h:26:
In file included from /Users/bennet/Downloads/rme-master/source/basemap.h:13:
/Users/bennet/Downloads/rme-master/source/map_allocator.h:11:11: warning: private field 'map' is not used [-Wunused-private-field]
        BaseMap& map;
                 ^
2 warnings and 2 errors generated.

**Comment by gpedro** [comment]
please, checkout latest version and try again.
