### ISSUE TITLE
Fill / Bucket tool

### ISSUE THREAD

**Issue by coldensjo** [hjnilsson/rme#246]
![photoshop_2018-09-30_00-33-29](https://user-images.githubusercontent.com/28816173/46251045-86058c00-c448-11e8-8059-36e7c1dbd3b5.png)

Would be a nice quality of life feature

**Comment by Mignari** [comment]
This already works with some limitations.

https://github.com/hjnilsson/rme/pull/230

**Comment by coldensjo** [comment]
![3ahuhyn](https://user-images.githubusercontent.com/28816173/46365850-e92a3500-c679-11e8-91e1-d4d372f6ed0a.png)
Doesn't work for me.

**Comment by Mignari** [comment]
Sorry, this is a feature for RME 3.5 or higher
I'll generate a new release as soon as possible

**Comment by Mignari** [comment]
https://github.com/hjnilsson/rme/releases/tag/v3.5
