### ISSUE TITLE
Item search window gives no options when adding an item to a container

### ISSUE THREAD

**Issue by Sickness-chan** [hjnilsson/rme#253]
As the title says, you get no options to search for specific items when you try to add an item to a container, such as a quest chest. Everything is greyed out, which makes finding something you're looking for pretty painful. I'd suggest only disabling the checkbox for "Pickupable" and leave the other property filters enabled.

![](https://i.imgur.com/uktQk1W.png)

**Comment by CristoferMartins** [comment]
I have the same bug.

**Comment by Sickness-chan** [comment]
Yeah, I've already changed it for myself long ago, but it's not a good solution for the masses. It would allow you to add unmoveable items like walls into containers, which is gonna end bad for unexperienced people.
