### ISSUE TITLE
Saving map as text

### ISSUE THREAD

**Issue by boveloco** [hjnilsson/rme#261]
Due to i'ts binary model, the project managing with any source code versioning became really hard to deal with.

So my question is if there's any way to save the map as text, so we could use the better approach with versioning?

Thanks

**Comment by gpedro** [comment]
you shouldn't have problems versioning binary files because git lfs supports than

**Comment by boveloco** [comment]
Hello @gpedro.
The issue here isn't about the size of the file, but the changes that are made. 

Eg:
If I made a change to the map in a branch A, and, someone else makes a change in another branch B, if we merge both on master, i would have to choose between one or another, and worse, if they are behind of master, i could have lost every work on branch A and B. 

Got it?

**Comment by peonso** [comment]
You could use this to save it in JSON
https://otland.net/threads/a-generic-framework-for-programmatic-modification-of-otbm-files.258612/

**Comment by boveloco** [comment]
@peonso Thank you, i'll give it a try. 
:)
