### ISSUE TITLE
RME dont replace all items at same time.

### ISSUE THREAD

**Issue by Ackerzin** [hjnilsson/rme#262]
Im trying to replace items on my map, and when I use the replace function, it dont replaces all items, it starts replacing from northwest and coming to south east parts of the map, I need to replace 9999x times, because each time I replace, replace like one small part of the map only. Its a bug or its supposed to be like this?

**Comment by Mignari** [comment]
Try setting option Replace Count at menu File > Prefences > General (Tab) 
Large values may be slow or cause crashes

**Comment by Ackerzin** [comment]
Ah, Ok.
Thanks! <3
