### ISSUE TITLE
New "copy map" window

### ISSUE THREAD

**Issue by HeavenIsLost** [hjnilsson/rme#27]
Well, when you have a bad computer and you want to copy a large part of a map( like a continent ), you cant make a big selection because the map editor lags like a hell( because you need a big view to do this selection, and big view means drawing a lot of items and such ). So, its would be nice if the map editor have a window which users tells the rectangle( x,y,width,height ) they want to copy and the map editor will copy it to clipboard.

Being able to make selection in the minimap window would resolve the issue too.

Thanks in advance.

**Comment by Mignari** [comment]
It's a good feature. When copying a large area of the map is really a hell.

Something like:

![copy](http://s1.postimg.org/ysl3pwvin/map_selection.png)

What do you think of it?

**Comment by gpedro** [comment]
:+1:

**Comment by Geseth** [comment]
@hjnilsson it is in half-way. I suggest to improve the File>Import>Import map... with things that show @Mignari. It really help us.
