### ISSUE TITLE
RME MAP LOADING PROBLEM (MAP EDITOR STOP WORKING AT 11%)

### ISSUE THREAD

**Issue by SirPodlas** [hjnilsson/rme#273]
Hello !

I created a new map and today map stop loading (Map Editor stop working at 11% )
(others map normally loading)

Tibia 8.54
Win 8
RME 3.5

Helpme if u can :) 
Thx

**Comment by Elime1** [comment]
Can you share the map files?

**Comment by SirPodlas** [comment]
Yea i can.
Is there any program to edit the OTBM file in the "scrapbook"?

**Comment by Elime1** [comment]
scrapbook?

**Comment by SirPodlas** [comment]
Oh.. bad translation :P 

the program that I can use to read the OTBM file code, something like that ?

**Comment by Elime1** [comment]
If you share your map with us (and we get the same problem when we open it) then we would be able to debug it and hopefully see where it goes wrong.

**Comment by SirPodlas** [comment]
https://drive.google.com/open?id=1Qb3iZKqKzqneM2kJUHtPZJ81OHaAApu5

**Comment by Elime1** [comment]
Your map was saved with Remere's Map Editor 2.2. We are currently at version 3.5. Please use the latest version available. https://github.com/hjnilsson/rme/releases

**Comment by SirPodlas** [comment]
Oh okey, my bad. So.. if posible to repair this?

**Comment by Elime1** [comment]
A bunch of tiles have invalid values. When I skip them it looks like a lot is missing:
![world](https://user-images.githubusercontent.com/9988754/61558055-42771f80-aa66-11e9-9e11-d1cedc46061a.png)

Maybe if you open it in RME 2.2 instead? Not sure how that version differs.
