### ISSUE TITLE
Choose items window bugged

### ISSUE THREAD

**Issue by diasreuf** [hjnilsson/rme#277]
Hello,

If I try to add an item to a box, the window that opens to choose items don't have any filtering options.

I'm using the compiled v3.5 x64 from this repository since i can't compile.

![Sem título](https://user-images.githubusercontent.com/34462998/62667017-3fcc6380-b95c-11e9-9104-8ead9c219cbd.png)

**Comment by Mignari** [comment]
Hi, the v3.5 will show all pickupable items
This has already been fixed in the development release (v3.6)
