### ISSUE TITLE
Compiling on Mint 18.2

### ISSUE THREAD

**Issue by cellss** [hjnilsson/rme#280]
No erros before "make"

> Scanning dependencies of target rme
[  1%] Building CXX object CMakeFiles/rme.dir/source/about_window.cpp.o
[  2%] Building CXX object CMakeFiles/rme.dir/source/action.cpp.o
[  3%] Building CXX object CMakeFiles/rme.dir/source/application.cpp.o
[  4%] Building CXX object CMakeFiles/rme.dir/source/artprovider.cpp.o
In file included from /home/usuario/Downloads/new/rme/source/artprovider.cpp:19:0:
/home/usuario/Downloads/new/rme/source/artprovider.h:48:96: error: expected ‘;’ at end of member declaration
  virtual wxBitmap CreateBitmap(const wxArtID& id, const wxArtClient& client, const wxSize& size) wxOVERRIDE;
                                                                                                ^
/home/usuario/Downloads/new/rme/source/artprovider.h:48:98: error: ‘wxOVERRIDE’ does not name a type
  virtual wxBitmap CreateBitmap(const wxArtID& id, const wxArtClient& client, const wxSize& size) wxOVERRIDE;
                                                                                                  ^
CMakeFiles/rme.dir/build.make:134: recipe for target 'CMakeFiles/rme.dir/source/artprovider.cpp.o' failed
make[2]: *** [CMakeFiles/rme.dir/source/artprovider.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/usuario/Downloads/new/rme/source/application.cpp:33:0:
/home/usuario/Downloads/new/rme/source/artprovider.h:48:96: error: expected ‘;’ at end of member declaration
  virtual wxBitmap CreateBitmap(const wxArtID& id, const wxArtClient& client, const wxSize& size) wxOVERRIDE;
                                                                                                ^
/home/usuario/Downloads/new/rme/source/artprovider.h:48:98: error: ‘wxOVERRIDE’ does not name a type
  virtual wxBitmap CreateBitmap(const wxArtID& id, const wxArtClient& client, const wxSize& size) wxOVERRIDE;
                                                                                                  ^
CMakeFiles/rme.dir/build.make:110: recipe for target 'CMakeFiles/rme.dir/source/application.cpp.o' failed
make[2]: *** [CMakeFiles/rme.dir/source/application.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rme.dir/all' failed
make[1]: *** [CMakeFiles/rme.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Fibrosis** [comment]
Same issue on Debian 9.
Looks like the culprit is commit 09097cbe4e02a913efaac6fc0e751970b2bb33af when artprovider.h was first added.

**Comment by Mignari** [comment]
Try removing wxOVERRIDE
artprovider.h line 48

https://github.com/hjnilsson/rme/blob/master/source/artprovider.h#L48
