### ISSUE TITLE
Compiling warning [part 2]

### ISSUE THREAD

**Issue by EPuncker** [hjnilsson/rme#294]
![2020-01-28 20_02_04-RME - Microsoft Visual Studio](https://user-images.githubusercontent.com/4684880/73313146-333d0f80-4209-11ea-81f3-69b2715bacad.png)

just a warning I get when compiling it on MVS 2017, Release, x64, Windows 10

(btw I'm feeling there will be more after those are fixed too 😝 )

**Comment by Sickness-chan** [comment]
well, u know how to fix them now from my PR, just make your own PR with the fixes

**Comment by EPuncker** [comment]
yes, thanks :)
