### ISSUE TITLE
Is it possible to put to save maps in clientid?

### ISSUE THREAD

**Issue by dudantas** [hjnilsson/rme#302]
Hello. I'm converting a base to client id
This PR has an example: https://github.com/otland/forgottenserver/pull/2898

I would like to know the possibility of RME to support saving maps in client id. It would be nice to have this feature in the editor.

Is it possible to put to save maps in clientid?

We have the idea of converting the entire OTServBR - Global repository to client id and RME (this is already underway, little is missing)
And this feature would already help a lot in this migration.

**Comment by diath** [comment]
You could try replacing ``id`` with ``g_items[id].clientID`` in the following functions:
https://github.com/hjnilsson/rme/blob/afb7417a5562baabd2bd455b665ea22fc7335125/source/iomap_otbm.cpp#L227
https://github.com/hjnilsson/rme/blob/afb7417a5562baabd2bd455b665ea22fc7335125/source/iomap_otbm.cpp#L241
https://github.com/hjnilsson/rme/blob/afb7417a5562baabd2bd455b665ea22fc7335125/source/iomap_otbm.cpp#L373

**Comment by dudantas** [comment]
> You could try replacing `id` with `g_items[id].clientID` in the following functions:
> https://github.com/hjnilsson/rme/blob/afb7417a5562baabd2bd455b665ea22fc7335125/source/iomap_otbm.cpp#L227
> 
> 
> https://github.com/hjnilsson/rme/blob/afb7417a5562baabd2bd455b665ea22fc7335125/source/iomap_otbm.cpp#L241
> 
> 
> https://github.com/hjnilsson/rme/blob/afb7417a5562baabd2bd455b665ea22fc7335125/source/iomap_otbm.cpp#L373

Thanks.
I will test and return with the answer.

Just one more question: Would it be an obstacle to implement this in RME here from the repository in the not too distant future?

**Comment by dudantas** [comment]
@diath thank you very much, it worked perfectly.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/78865226-96220280-7a13-11ea-871f-a61ead30766d.png)
