### ISSUE TITLE
Problem with compiling Ubuntu 20.04 and Arch

### ISSUE THREAD

**Issue by whiteprojectcrixu** [hjnilsson/rme#314]
```
34%] Building CXX object CMakeFiles/rme.dir/source/house_brush.cpp.o
In file included from /home/crixu/Project/rme/source/graphics.cpp:25:
/home/crixu/Project/rme/source/filehandle.h: In member function ‘bool FileReadHandle::getType(T&) [with T = unsigned char]’:
/home/crixu/Project/rme/source/filehandle.h:98:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   98 |   fread(&ref, sizeof(ref), 1, file);
      |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/crixu/Project/rme/source/filehandle.h: In member function ‘bool FileReadHandle::getType(T&) [with T = int]’:
/home/crixu/Project/rme/source/filehandle.h:98:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
/home/crixu/Project/rme/source/filehandle.h: In member function ‘bool FileReadHandle::getType(T&) [with T = signed char]’:
/home/crixu/Project/rme/source/filehandle.h:98:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
/home/crixu/Project/rme/source/filehandle.h: In member function ‘bool FileReadHandle::getType(T&) [with T = unsigned int]’:
/home/crixu/Project/rme/source/filehandle.h:98:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
/home/crixu/Project/rme/source/filehandle.h: In member function ‘bool FileReadHandle::getType(T&) [with T = short unsigned int]’:
/home/crixu/Project/rme/source/filehandle.h:98:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
/home/crixu/Project/rme/source/gui.cpp: In static member function ‘static wxString GUI::GetDataDirectory()’:
/home/crixu/Project/rme/source/gui.cpp:129:13: warning: catching polymorphic type ‘class std::bad_cast’ by value [-Wcatch-value=]
  129 |  catch(std::bad_cast)
      |             ^~~~~~~~
/home/crixu/Project/rme/source/gui.cpp: In static member function ‘static wxString GUI::GetExecDirectory()’:
/home/crixu/Project/rme/source/gui.cpp:146:13: warning: catching polymorphic type ‘class std::bad_cast’ by value [-Wcatch-value=]
  146 |  catch(std::bad_cast)
      |             ^~~~~~~~
/home/crixu/Project/rme/source/gui.cpp: In member function ‘void GUI::ShowWelcomeDialog(const wxBitmap&)’:
/home/crixu/Project/rme/source/gui.cpp:1173:106: error: ‘class MainFrame’ has no member named ‘FromDIP’
 1173 |     welcomeDialog = newd WelcomeDialog(__W_RME_APPLICATION_NAME__, "Version " + __W_RME_VERSION__, root->FromDIP(wxSize(800, 480)), icon, recent_files);
      |                                                                                                          ^~~~~~~
make[2]: *** [CMakeFiles/rme.dir/build.make:466: CMakeFiles/rme.dir/source/gui.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/rme.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by aspiraboo** [comment]
Hello, have a same issue, my OS is derived of Arch Linux, called Manjaro Linux.
In wxgtk3.0.5.1-1 has missing function FromDIP if you install a default package "In this date 03/08/2020".
My solution is change the version of wxgtk3, from wxgtk3.0.5.1-1 to wxgtk3.1.4-1
On Arch use this package in AUR: https://aur.archlinux.org/packages/wxgtk3-dev/

**Comment by whiteprojectcrixu** [comment]
I used old version 3.6 is working on Ubuntu, You can try this

**Comment by Machine-Hum** [comment]
> Hello, have a same issue, my OS is derived of Arch Linux, called Manjaro Linux.
> In wxgtk3.0.5.1-1 has missing function FromDIP if you install a default package "In this date 03/08/2020".
> My solution is change the version of wxgtk3, from wxgtk3.0.5.1-1 to wxgtk3.1.4-1
> On Arch use this package in AUR: https://aur.archlinux.org/packages/wxgtk3-dev/

Do you have any more info? I install all that from the AUR  (It made me uninstall some stuff below)

```
:: wxgtk2-dev and wxgtk2 are in conflict (wxgtk). Remove wxgtk2? [y/N] y
:: wxgtk-common-dev and wxgtk-common are in conflict. Remove wxgtk-common? [y/N] y
:: wxgtk3-dev and wxgtk3 are in conflict. Remove wxgtk3? [y/N] y
```

Getting include errors.

```
In file included from /home/machinehum/war_server/rme/source/action.cpp:18:
/home/machinehum/war_server/rme/source/main.h:54:10: fatal error: wx/defs.h: No such file or directory
   54 | #include <wx/defs.h>
      |          ^~~~~~~~~~~
```

**Comment by Machine-Hum** [comment]
> > Hello, have a same issue, my OS is derived of Arch Linux, called Manjaro Linux.
> > In wxgtk3.0.5.1-1 has missing function FromDIP if you install a default package "In this date 03/08/2020".
> > My solution is change the version of wxgtk3, from wxgtk3.0.5.1-1 to wxgtk3.1.4-1
> > On Arch use this package in AUR: https://aur.archlinux.org/packages/wxgtk3-dev/
> 
> Do you have any more info? I install all that from the AUR (It made me uninstall some stuff below)
> 
> ```
> :: wxgtk2-dev and wxgtk2 are in conflict (wxgtk). Remove wxgtk2? [y/N] y
> :: wxgtk-common-dev and wxgtk-common are in conflict. Remove wxgtk-common? [y/N] y
> :: wxgtk3-dev and wxgtk3 are in conflict. Remove wxgtk3? [y/N] y
> ```
> 
> Getting include errors.
> 
> ```
> In file included from /home/machinehum/war_server/rme/source/action.cpp:18:
> /home/machinehum/war_server/rme/source/main.h:54:10: fatal error: wx/defs.h: No such file or directory
>    54 | #include <wx/defs.h>
>       |          ^~~~~~~~~~~
> ```

Derp...
`cmake .. && make`

**Comment by mofdes** [comment]
For the Debian and Ubuntu-based distribution installing latest development release of the wxWidget (3.1.4) should fix the issue. Step-by-step guide how to do that: https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries

**Comment by whiteprojectcrixu** [comment]
> For the Debian and Ubuntu-based distribution installing latest development release of the wxWidget (3.1.4) should fix the issue. Step-by-step guide how to do that: https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries

Thanks this is fixing problem on ubuntu 20.04 Focial i closed this problem
