### ISSUE TITLE
"Teleports To" Markers

### ISSUE THREAD

**Issue by dominique120** [hjnilsson/rme#49]
It would be extremely useful to have a feature that displays markers at the exit points of teleporters. Would this be hard to implement?

If its already implemented please tell me how to enable it.

**Comment by EPuncker** [comment]
something like http://i.imgur.com/48smSGL.png

yeah would be great!

I would like to suggest the addition of a menu option to check all teleports for invalid destination coordinates (that leads to invalid location) as well

**Comment by Geseth** [comment]
It will be really useful.
