### ISSUE TITLE
Two proposals: check for double walls and invalid town temple position

### ISSUE THREAD

**Issue by EPuncker** [hjnilsson/rme#55]
the title is kinda self explanatory, I remember that simOne did have an option or whatever it was, to warn user about two walls placed on the same place and I think it would be came in hand at RME (ofc there are map that need two walls at same place, that is why it needs an ignore option). The second one is that there are lots of maps that have towns at town list but the coordinates of the town doesn't exists anymore, so maybe we can add a check just like the teleport destination thing.

Bonus suggestion: make so when double clicking the town at town list the map editor takes you to there, just like when searching items etc. (kinda painful to copy coordinates and paste them at ctrl+g by hand.

**Comment by HeavenIsLost** [comment]
signed +1
