### ISSUE TITLE
Errors: RME Freezing, wxWidgets Debug Alert and Unhandled exception; And my suggestion

### ISSUE THREAD

**Issue by FelipeCFerro** [hjnilsson/rme#62]
Explanation and first problem: Hello! I've been working in a big map of Hoenn (3th generation of Pokemon). I'm using 8.54 extended spr and dat files. Map dimensions are 6350 x 4505.
Today morning I've finished the terrain part of the project and filled the edges of the map with water. I've tried to export the minimaps and it worked. After that I used the water brush to fill some more free space and saved the project. I don't know why it stopped exporting minimaps or loading with a server. Is there any way I can save my work? Is there any way I can open .otbm file and select some tiles to be copied? Something like that.
I'm not asking for someone to do this for me. I just want to know if someone could tell me a way to solve it.

The second problem that I've noticed with that otbm file is that most of the times I can't load the map with RME while another project is already opened, because this error message appears:
![captura de tela 2014-06-30 as 01 39 28](https://cloud.githubusercontent.com/assets/5500781/3425870/553feeca-0012-11e4-9cca-0c0873aeb7e1.png)

The third problem happens when I try to import this map into another one. When I try it an Unhandled exception alert comes out:
![captura de tela 2014-06-30 as 02 09 13](https://cloud.githubusercontent.com/assets/5500781/3425968/7dd04878-0015-11e4-8898-f96bafae613d.png)

The project:
I had a backup but after I've noticed that the exporting was working I saved it over the backup because I thought it wouldn't be problems anymore.
This is the project. And I really don't want to loose it. =/
![captura de tela 2014-06-29 as 19 39 29](https://cloud.githubusercontent.com/assets/5500781/3424749/a74b4c3a-ffe2-11e3-9c8c-e2984c3e6417.png)

Suggestion:
Since I'm not a good programmer I don't know how to make it, but I think that there could be a button that allow the user to insert two coordinates to select a square area of the map to be exported into a new otbm file that would be saved just like this. If someone guide me to where is the code I can edited to make it I could try it.

**Comment by gpedro** [comment]
please, checkout latest version and try again.
