### ISSUE TITLE
New rme feature( related to actions and unique )

### ISSUE THREAD

**Issue by HeavenIsLost** [hjnilsson/rme#73]
I'm just missing a tool that i think would be really nice: Automatic replace unique/action ids on the map. Its just a box with a two ranges( from id to id ): one range to the old ids and a another to the new ids. Just choose if its action or unique and rme will find the items which have the id and change it to the new one.

**Comment by gpedro** [comment]
wow. this feature LGTM. @Mignari we can mark this feature in 3.2 milestone?
