### ISSUE TITLE
remeresmapeditor.com down

### ISSUE THREAD

**Issue by tarantonio** [hjnilsson/rme#83]
as tittle says..
I'm getting 502 error bad gateway

**Comment by hjnilsson** [comment]
Thank you for the notice. I've fixed the issue. :)

On Friday, January 2, 2015, tarantonio <notifications@github.com> wrote:

> as tittle says..
> I'm getting 502 error bad gateway
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjnilsson/rme/issues/83>.
>


-- 
// Hampus Nilsson

**Comment by divinity76** [comment]
and it works for me.. close this issue?
