### ISSUE TITLE
Ubuntu compile problem

### ISSUE THREAD

**Issue by nexxxx** [hjnilsson/rme#87]
/Pobrane/rme-master/build$ make -j `nproc`
[  1%] [  2%] Building CXX object CMakeFiles/rme.dir/source/about_window.cpp.o
Building CXX object CMakeFiles/rme.dir/source/action.cpp.o
In file included from /usr/include/wx-2.8/wx/glcanvas.h:54:0,
                 from /home/bmw/Pobrane/rme-master/source/main.h:66,
                 from /home/bmw/Pobrane/rme-master/source/action.cpp:20:
/usr/include/wx-2.8/wx/gtk/glcanvas.h:21:20: fatal error: GL/glu.h: No such file or directory
 #include <GL/glu.h>
                    ^
compilation terminated.
In file included from /usr/include/wx-2.8/wx/glcanvas.h:54:0,
                 from /home/bmw/Pobrane/rme-master/source/main.h:66,
                 from /home/bmw/Pobrane/rme-master/source/about_window.cpp:20:
/usr/include/wx-2.8/wx/gtk/glcanvas.h:21:20: fatal error: GL/glu.h: No such file or directory
 #include <GL/glu.h>
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/rme.dir/source/action.cpp.o] Error 1
make[2]: *** Oczekiwanie na niezakończone zadania....
make[2]: *** [CMakeFiles/rme.dir/source/about_window.cpp.o] Error 1
make[1]: *** [CMakeFiles/rme.dir/all] Błąd 2
make: *** [all] Error 2

How fix it?

**Comment by gpedro** [comment]
try to install the `libglu1-mesa-dev` package
