### ISSUE TITLE
MapDrawer::BlitCreature() L1301 "it.clientID" should be "it.id", it is the server id, not client id.

### ISSUE THREAD

**Issue by nneesshh** [hjnilsson/rme#90]
https://github.com/hjnilsson/rme/blob/master/source/map_drawer.cpp#L1301
BlitSpriteType(screenx, screeny, it.clientID, red, green, blue, alpha);

"it.clientID" should be "it.id", it is the server id, not client id.

**Comment by Mignari** [comment]
This has been fixed in the [e31c180](https://github.com/hjnilsson/rme/commit/e31c180df3b4a47cee4825557aa6657d2c5fdadc).
Thanks!
