### ISSUE TITLE
http://remeresmapeditor.com offline

### ISSUE THREAD

**Issue by Ravene** [hjnilsson/rme#93]
hi i wait 1/2month but website still offline someone can upload tibia.dat and spr 8.6 here or actiive website please?!

nginx

This site is not hosted on this server.

**Comment by hjnilsson** [comment]
Online again. :)

On Sat, May 30, 2015 at 9:30 AM, Ravene <notifications@github.com> wrote:

> hi i wait 1/2month but website still offline someone can upload tibia.dat
> and spr 8.6 here or actiive website please?!
>
> nginx
>
> This site is not hosted on this server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjnilsson/rme/issues/93>.
>



-- 
// Hampus Nilsson

**Comment by Ravene** [comment]
@hjnilsson dont work the same message
nginx

This site is not hosted on this server.
