### ISSUE TITLE
Export the map to image

### ISSUE THREAD

**Issue by JoseEduardo** [hjnilsson/rme#94]
Is there any way to export floor by floor to image? I know that this feature does not currently exist, but it will be that someone is willing to develop or at least indicate where to start?

thank you

**Comment by hjnilsson** [comment]
Floor by floor? You can just select "All floors" in the map export dialog?

**Comment by JoseEduardo** [comment]
But in this case it would be paragraph Export the minimap , What Do I Need And What basically the "Take screenshoot " does, but forms a que que do with the export Full map and not only what is being seen.
