### ISSUE TITLE
How to compile :s (linux)

### ISSUE THREAD

**Issue by vaizardx** [hjnilsson/rme#95]
Hello everyone
I'm new on Linux , and im using ubuntu 12.04
I need to know how install all libraries and compile the rme for me work in my map
Thanks all !

**Comment by Mignari** [comment]
I'm not a Linux user, but I compile it with [QtCreator](http://sourceforge.net/projects/qtcreator.mirror/) on Ubuntu 14.04.

First of all, install gcc, cmake, boost, mesa, wxWidgets and libarchive using sudo.

**Comment by vaizardx** [comment]
OK , but my principal problemas is how to install gcc, cmake, boost, mesa, wxWidgets.
Can you help me ?

**Comment by gpedro** [comment]
@vaizardx try install this packages using `apt-get`

**Comment by vaizardx** [comment]
But some packages like mesa , wxWidgets do not exist.
I need know full name ? What is ?

**Comment by gpedro** [comment]
mesa: `libglu1-mesa-dev`
wxWidgets: `libwxgtk2.8-dev`

**Comment by gpedro** [comment]
@vaizardx you could compile?

**Comment by gpedro** [comment]
I updated the documentation to compile on Linux. Please, check [README.md](https://github.com/hjnilsson/rme/blob/master/README.md)
