### ISSUE TITLE
"expansion" request

### ISSUE THREAD

**Issue by dutchie1289** [hjnilsson/rme#99]
First things first, sorry if I'm at the wrong place.

I would like to see Item Properties action/uniqueids windows being updated with an extra field, the value field.

So you can create 1 quest door, actionid: 1000, value: 1.
And a second one: actionid: 1000, value: 2.

I hope you get and see my point, cause a lot of people will spare a lot of storage value numbers that way.

Greetings

**Comment by gpedro** [comment]
@Mignari @hjnilsson  this is possible?

**Comment by Mignari** [comment]
I don't know anything about action/unique ids.

**Comment by hjnilsson** [comment]
The new OTBM format allows arbitrary key / values for properties. Adding a "value" property would be a waste. Instead fix the dialog that allows adding any keys and values.
